# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
    - main
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/entra/Microsoft.Azure.WebJobs.Extensions.AuthenticationEvents/
    - sdk/entra/Microsoft.Azure.Entra.Authentication/

pr:
  branches:
    include:
    - main
    - feature/*
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/entra/Microsoft.Azure.WebJobs.Extensions.AuthenticationEvents/
    - sdk/entra/Microsoft.Azure.Entra.Authentication/

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: entra
    BuildSnippets: false
    ArtifactName: packages
    Artifacts:
    - name: Microsoft.Azure.WebJobs.Extensions.AuthenticationEvents
      safeName: MicrosoftAzureWebJobsExtensionsAuthenticationEvents
    - name: Microsoft.Azure.Entra.Authentication
      safeName: Microsoft.Azure.Entra.Authentication
